pull_request_rules:
  - name: request review from users and team when pull request is labeled with `review`
    conditions:
      - "#files>=1"
    actions:
      request_reviews:
        users:
          - "sudhanshuvlog"
      comment:
         message: "Requesting the Review from Sudhanshu"